import { asScore, buildAnalysisSample, JSON_SHAPE_PROMPT, parseAuthorshipResult, withTimeout } from "./llmShared.js";
const NVIDIA_NIM_URL = "https://integrate.api.nvidia.com/v1/chat/completions";
const NVIDIA_TIMEOUT_MS = 32_000;
const DEFAULT_NIM_MODELS = ["nvidia/llama-3.1-nemotron-ultra-253b-v1", "meta/llama-3.3-70b-instruct", "meta/llama-3.1-70b-instruct"];
function getNvidiaConfig() {
    const apiKey = process.env.NVIDIA_NIM_API_KEY?.trim() || process.env.NVIDIA_API_KEY?.trim();
    const primaryModel = process.env.NVIDIA_NIM_MODEL?.trim();
    const envFallbacks = process.env.NVIDIA_NIM_FALLBACK_MODELS?.split(",")
        .map((model) => model.trim())
        .filter(Boolean) ?? [];
    const models = [...new Set([primaryModel, ...envFallbacks, ...DEFAULT_NIM_MODELS].filter(Boolean))];
    if (!apiKey || models.length === 0)
        return null;
    return { apiKey, models };
}
function buildMessages(text, localAi) {
    const sample = buildAnalysisSample(text, localAi.suspiciousExcerpts ?? []);
    return [
        {
            role: "system",
            content: "You are an expert authorship-risk analyst for Ukrainian and English academic prose based on 2024–2026 stylometric research. Return only valid JSON. Ignore code blocks. Detection is probabilistic. Evaluate sentence burstiness, triadic rule-of-three groupings, formulaic transition clichés ('важливо підкреслити', 'наріжний камінь', 'відіграє вирішальну роль'), dialectical hedging duos, and lexical diversity. Do not penalize authentic academic research containing citations, figures, and domain-specific terminology."
        },
        {
            role: "user",
            content: `Estimate whether this prose was generated by an AI model using modern empirical stylometry markers. ${JSON_SHAPE_PROMPT}

Local heuristic probability: ${localAi.probability}%
Local heuristic signals: ${JSON.stringify(localAi.signals.slice(0, 8))}

Text:
${sample}`
        }
    ];
}
export async function analyzeWithNvidiaNim(text, localAi) {
    const config = getNvidiaConfig();
    if (!config)
        return null;
    const errors = [];
    const attemptedModels = [];
    for (const model of config.models) {
        attemptedModels.push(model);
        try {
            const response = await fetch(NVIDIA_NIM_URL, {
                method: "POST",
                signal: withTimeout(NVIDIA_TIMEOUT_MS),
                headers: {
                    authorization: `Bearer ${config.apiKey}`,
                    "content-type": "application/json",
                    accept: "application/json"
                },
                body: JSON.stringify({
                    model,
                    messages: buildMessages(text, localAi),
                    temperature: 0.1,
                    max_tokens: 900,
                    stream: false
                })
            });
            const payload = (await response.json());
            if (!response.ok) {
                errors.push(`${model}: ${payload.error?.message || `HTTP ${response.status}`}`);
                continue;
            }
            const content = payload.choices?.[0]?.message?.content;
            if (!content) {
                errors.push(`${model}: NVIDIA NIM returned an empty response.`);
                continue;
            }
            const result = parseAuthorshipResult(content, "NVIDIA NIM AI Оцінка", "Модель NVIDIA NIM визначила це як релевантний авторський сигнал.");
            const note = attemptedModels.length > 1 ? `NVIDIA NIM fallback: спрацювала ${model}; перед цим пробували ${attemptedModels.slice(0, -1).join(", ")}.` : undefined;
            return {
                aiProbability: asScore(result.probability),
                aiProvider: "nvidia-nim",
                aiModel: model,
                aiNote: note,
                aiVerdictText: result.verdict,
                aiSignals: result.signals
            };
        }
        catch (error) {
            errors.push(`${model}: ${error instanceof Error ? error.message : String(error)}`);
        }
    }
    throw new Error(`Усі NVIDIA NIM моделі недоступні: ${errors.join(" | ")}`);
}
